/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frm;

import Controladores.MostrarProductos;
import Entidades.Producto;
import Entidades.Productovista;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author ittov
 */
public class FrmProductos extends javax.swing.JFrame {
   public static String producto,precio,id,precioventa,inventario;
    /**
     * Creates new form FrmProductos
     */
    public FrmProductos() {
        initComponents();
        this.setLocationRelativeTo(null);
        buscar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        txtBuscadorserie = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblproductos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        pnbarra = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelar.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 200, 50));

        txtBuscadorserie.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        txtBuscadorserie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorserieKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscadorserie, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 410, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        btnSeleccionar.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnSeleccionar.setContentAreaFilled(false);
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 200, 50));

        tblproductos.setBackground(new java.awt.Color(11, 55, 68));
        tblproductos.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        tblproductos.setForeground(new java.awt.Color(255, 255, 255));
        tblproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblproductos.setGridColor(new java.awt.Color(255, 255, 255));
        tblproductos.setInheritsPopupMenu(true);
        tblproductos.getTableHeader().setResizingAllowed(false);
        tblproductos.getTableHeader().setReorderingAllowed(false);
        tblproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblproductosMouseClicked(evt);
            }
        });
        tblproductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblproductosKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblproductos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 820, 260));

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Serie");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 840, 530));

        pnbarra.setBackground(new java.awt.Color(255, 166, 33));
        pnbarra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        pnbarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnbarraMouseDragged(evt);
            }
        });
        pnbarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnbarraMousePressed(evt);
            }
        });
        pnbarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Producto");
        pnbarra.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        getContentPane().add(pnbarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 30));

        lblFondo.setBackground(new java.awt.Color(153, 153, 153));
        lblFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblFondo.setMaximumSize(new java.awt.Dimension(1111, 800));
        lblFondo.setOpaque(true);
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents
int xx,yy;
    private void pnbarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnbarraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x-xx, y-yy);

    }//GEN-LAST:event_pnbarraMouseDragged

    private void pnbarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnbarraMousePressed
        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_pnbarraMousePressed
   void seleccionar(){
       int fila = tblproductos.getSelectedRow();
       if(fila >=0){
        String id = String.valueOf(tblproductos.getModel().getValueAt(tblproductos.getSelectedRow(), 0));
      producto= String.valueOf(tblproductos.getModel().getValueAt(tblproductos.getSelectedRow(), 1));
       precio = String.valueOf(tblproductos.getModel().getValueAt(tblproductos.getSelectedRow(), 5));
       precioventa= String.valueOf(tblproductos.getModel().getValueAt(tblproductos.getSelectedRow(), 3));
       inventario =String.valueOf(tblproductos.getModel().getValueAt(tblproductos.getSelectedRow(), 9));
       
       int inv = Integer.parseInt(inventario);
       if(inv> 0 ){
       inicio.cambioproducto();
          this.dispose();
       }
       else{
       JOptionPane.showMessageDialog(null, "Ya no hay mas productos en el inventario");
       }
       }
       else{
           JOptionPane.showMessageDialog(null,"Seleccione una fila");
       }
}
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtBuscadorserieKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorserieKeyReleased
     buscar();
    }//GEN-LAST:event_txtBuscadorserieKeyReleased

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        seleccionar();
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void tblproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblproductosMouseClicked
     if(evt.getClickCount()==2){
         seleccionar();
       }
    }//GEN-LAST:event_tblproductosMouseClicked

    private void tblproductosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblproductosKeyReleased
        tblproductos.getInputMap(tblproductos.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0,false), "selectColumnCell");
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            seleccionar();
       }
    }//GEN-LAST:event_tblproductosKeyReleased
     Producto p = new Producto(); public void buscar(){
     String Titulo[]={"ID","Producto","Serie","Costo","Margen","Precio","Marca","Descripcion","Proveedor","Inventario"};
DefaultTableModel bc = new DefaultTableModel(null, Titulo){
    @Override
    public boolean isCellEditable(int row, int column) {
        return false;
    }
};
        Productovista pr = new Productovista();
    pr.setSerie(txtBuscadorserie.getText());
    MostrarProductos mp = new MostrarProductos();
    ArrayList<Productovista> Cl= mp.BuscarProducto(pr);
    Iterator i =  Cl.iterator();
    String Filas[] = new String[10];
    while (i.hasNext()) {        
        Productovista p;
        p= (Productovista)i.next();
        Filas[0]=String.valueOf(p.getId_Producto());
        Filas[1]= p.getProducto();
        Filas[2]=p.getSerie();
         Filas[3]=String.valueOf(p.getCosto());
          Filas[4]=String.valueOf(p.getMargen());
        Filas[5]=String.valueOf(p.getPrecio());
        Filas[6]=p.getMarca();
         Filas[7]=p.getDescripcion();
           Filas[8]=p.getProveedor();
             Filas[9]=String.valueOf(p.getInventario());
        bc.addRow(Filas);
         
    }
  
tblproductos.setModel(bc);
        tabla();
}
    void comprobacioninventario(){
       String inventario ;
       
        for (int i = 0; i < tblproductos.getRowCount(); i++) {
            inventario = String.valueOf(tblproductos.getModel().getValueAt(i, 9));
            int inv = Integer.parseInt( inventario);
            if(inv >0 && inv <20){
            
         
            }
            else if(inv >=20 && inv <60){
            this.setForeground(Color.YELLOW);
            }
             else if(inv >=60 ){
            this.setForeground(Color.green);
            }
        }
    }
    public  void tabla(){
        JTableHeader th = tblproductos.getTableHeader();
        Font fuente = new Font("Century Schoolbook", Font.PLAIN, 14);
th.setFont(fuente); 
tblproductos.getColumnModel().getColumn(1).setPreferredWidth(150);
tblproductos.getColumnModel().getColumn(7).setPreferredWidth(200);
//tblproductos.removeColumn(tblproductos.getColumnModel().getColumn(0));
//tblproductos.removeColumn(tblproductos.getColumnModel().getColumn(2));
//tblproductos.removeColumn(tblproductos.getColumnModel().getColumn(2));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JPanel pnbarra;
    private javax.swing.JTable tblproductos;
    public static javax.swing.JTextField txtBuscadorserie;
    // End of variables declaration//GEN-END:variables
}
