package Frm;
import javax.swing.JOptionPane;
import Animacion.Animacion;
import Controladores.MostrarCliente;
import Controladores.MostrarEmpleado;
import Controladores.MostrarProductos;
import Entidades.Clientes;
import Entidades.Empleado;
import Entidades.Productovista;
import java.awt.Font;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

 
public class inicio extends javax.swing.JFrame {
    static double preciocompra;
    static int inventario;
    public  static  void cambio(){
   txtCliente.setText( Tpersona.cliente);
   txtDui.setText(Tpersona.dui);
   txtdireccion.setText(Tpersona.direccion);
    }
     public  static  void cambioproducto(){
         inventario = Integer.parseInt(FrmProductos.inventario);
   int existencia=0 ,fil=0 ;
    for (int i = 0; i < tblventa.getRowCount(); i++) {
 if(tblventa.getValueAt(i, 0).toString().equals(FrmProductos.producto)){
     existencia = 1;
     fil = i;
 } 
    } 
    if(existencia == 1){
       int cantidad = Integer.parseInt(tblventa.getValueAt(fil, 1).toString());
    if(inventario>cantidad){
    txtproducto.setText( FrmProductos.producto);
   txtprecio.setText(FrmProductos.precio);
   txtTotal.setText(FrmProductos.precio);
   preciocompra =Double.parseDouble(FrmProductos.precioventa);
   
    }
    else{
        JOptionPane.showMessageDialog(null, "ya se agrego el inventario completo de este producto");
    }
    }else{
     txtproducto.setText( FrmProductos.producto);
   txtprecio.setText(FrmProductos.precio);
   txtTotal.setText(FrmProductos.precio);
   preciocompra =Double.parseDouble(FrmProductos.precioventa);
    }
    }
   

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
      lblSelect.setVisible(true);
        lblSelect1.setVisible(false);
         lblSelect2.setVisible(false);
          lblSelect3.setVisible(false);
           pnProducto.setVisible(false);
           pnventa.setVisible(true);
           pncliente.setVisible(false); 
           tabla();
           fecha();
           buscar();
           buscarproducto();
           cargarcombo();
    }       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnBarra = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        pnProducto = new javax.swing.JPanel();
        pntabla1 = new javax.swing.JPanel();
        txtbuscarpro = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();
        pnventa = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        bntAgregarCliente = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        calendario = new com.toedter.calendar.JDateChooser();
        txtCliente = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtDui = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblventa = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        TpVentas = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtproducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        btnbuscarProductos = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bntmenos = new javax.swing.JButton();
        btnAgregaPro = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        bntAgregar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        CBXVendedor = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        TxtTotalventa = new javax.swing.JTextField();
        pncliente = new javax.swing.JPanel();
        pnnombre = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        pntabla = new javax.swing.JPanel();
        txtbuscarC = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMcliente = new javax.swing.JTable();
        PnMenu = new javax.swing.JPanel();
        btnVentas = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnAbono = new javax.swing.JButton();
        BtnCerrar = new javax.swing.JButton();
        lblSelect = new javax.swing.JLabel();
        lblSelect1 = new javax.swing.JLabel();
        lblSelect2 = new javax.swing.JLabel();
        lblSelect3 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1380, 770));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnBarra.setBackground(new java.awt.Color(204, 153, 0));
        PnBarra.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        PnBarra.setForeground(new java.awt.Color(0, 38, 34));
        PnBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setDisabledIcon(null);
        btnCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar1.png"))); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        PnBarra.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, 70, 48));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimizar.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimizar1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        PnBarra.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 46, 50));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-de-menu-de-tres-lineas-horizontales.png"))); // NOI18N
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-de-menu-de-tres-lineas-horizontales1.png"))); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        PnBarra.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 50));

        getContentPane().add(PnBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 50));

        pnProducto.setOpaque(false);
        pnProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pntabla1.setOpaque(false);
        pntabla1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtbuscarpro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarproKeyReleased(evt);
            }
        });
        pntabla1.add(txtbuscarpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 570, 30));

        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tblProducto.setBackground(new java.awt.Color(11, 55, 68));
        tblProducto.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        tblProducto.setForeground(new java.awt.Color(255, 255, 255));
        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblProducto.setGridColor(new java.awt.Color(255, 255, 255));
        tblProducto.setInheritsPopupMenu(true);
        tblProducto.getTableHeader().setResizingAllowed(false);
        tblProducto.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tblProducto);

        pntabla1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 890, 400));

        pnProducto.add(pntabla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1100, 740));

        getContentPane().add(pnProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 1100, 730));

        pnventa.setBackground(new java.awt.Color(102, 102, 102));
        pnventa.setOpaque(false);
        pnventa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2)), "Datos de Ventas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cliente:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 20));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dui:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 80, 20));

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dirección:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 20));

        txtdireccion.setEditable(false);
        txtdireccion.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jPanel3.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 620, 30));

        bntAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar (1).png"))); // NOI18N
        bntAgregarCliente.setBorderPainted(false);
        bntAgregarCliente.setContentAreaFilled(false);
        bntAgregarCliente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar (2).png"))); // NOI18N
        bntAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAgregarClienteActionPerformed(evt);
            }
        });
        jPanel3.add(bntAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 40, 40));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa-1.png"))); // NOI18N
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 50, 40));

        calendario.setDateFormatString("dd-mm-yyyy");
        calendario.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jPanel3.add(calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 190, 30));

        txtCliente.setEditable(false);
        txtCliente.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jPanel3.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 400, 30));

        jLabel15.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Fecha:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 20));

        txtDui.setEditable(false);
        txtDui.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jPanel3.add(txtDui, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 240, 30));

        pnventa.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 770, 180));

        tblventa.setBackground(new java.awt.Color(11, 55, 68));
        tblventa.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        tblventa.setForeground(new java.awt.Color(255, 255, 255));
        tblventa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Total"
            }
        ));
        tblventa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblventa.setGridColor(new java.awt.Color(255, 255, 255));
        tblventa.setSelectionBackground(new java.awt.Color(0, 0, 51));
        tblventa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblventa);

        pnventa.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 790, 130));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vender.png"))); // NOI18N
        jButton8.setText("Vender");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vender2.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        pnventa.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, 220, 80));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/noventa.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/noventa1.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnventa.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 300, 220, 80));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminarProducto.png"))); // NOI18N
        jButton10.setText("eliminar producto");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton10.setContentAreaFilled(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminarProducto1.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        pnventa.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, 220, 80));

        TpVentas.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Productos:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 20));

        txtproducto.setEditable(false);
        txtproducto.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        txtproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproductoActionPerformed(evt);
            }
        });
        jPanel2.add(txtproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 400, 30));

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Vendedor:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 100, 20));

        txtprecio.setEditable(false);
        txtprecio.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jPanel2.add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 80, 30));

        btnbuscarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        btnbuscarProductos.setBorderPainted(false);
        btnbuscarProductos.setContentAreaFilled(false);
        btnbuscarProductos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa-1.png"))); // NOI18N
        btnbuscarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarProductosActionPerformed(evt);
            }
        });
        jPanel2.add(btnbuscarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 50, 30));

        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Precio:   $");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, 20));

        txtCantidad.setEditable(false);
        txtCantidad.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad.setText("1");
        jPanel2.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 60, 30));

        txtTotal.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jPanel2.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 80, 30));

        jLabel10.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Precio de venta  $");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 180, 20));

        bntmenos.setIcon(new javax.swing.ImageIcon("C:\\Users\\ittov\\Desktop\\diseño\\menos.png")); // NOI18N
        bntmenos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        bntmenos.setBorderPainted(false);
        bntmenos.setContentAreaFilled(false);
        bntmenos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntmenos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bntmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntmenosActionPerformed(evt);
            }
        });
        jPanel2.add(bntmenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 40, 30));

        btnAgregaPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/masb.png"))); // NOI18N
        btnAgregaPro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnAgregaPro.setContentAreaFilled(false);
        btnAgregaPro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregaPro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnAgregaPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregaProActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregaPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 160, 40));

        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Agregar");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, 20));

        bntAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/masb.png"))); // NOI18N
        bntAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        bntAgregar.setBorderPainted(false);
        bntAgregar.setContentAreaFilled(false);
        bntAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntAgregar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bntAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(bntAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, 30));

        jLabel18.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Cantidad:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, 20));

        CBXVendedor.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        CBXVendedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(CBXVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 77, 280, -1));

        TpVentas.addTab("venta", jPanel2);

        pnventa.add(TpVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 780, 240));

        jLabel16.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total:");
        pnventa.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, -1, -1));

        TxtTotalventa.setEditable(false);
        TxtTotalventa.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        TxtTotalventa.setForeground(new java.awt.Color(255, 255, 255));
        TxtTotalventa.setText("0.00");
        TxtTotalventa.setOpaque(false);
        pnventa.add(TxtTotalventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 670, 160, 30));

        getContentPane().add(pnventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 1380, 750));

        pncliente.setOpaque(false);
        pncliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnnombre.setBackground(new java.awt.Color(0, 102, 102));
        pnnombre.setMinimumSize(new java.awt.Dimension(1100, 800));
        pnnombre.setPreferredSize(new java.awt.Dimension(1100, 1000));
        pnnombre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        pnnombre.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, 20));

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dirección:");
        pnnombre.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 100, 20));
        pnnombre.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 160, 30));

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nombre:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 20));
        jPanel5.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 160, 20));

        jLabel12.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Edad:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 90, 20));
        jPanel5.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 160, 20));

        pnnombre.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 270, 710));

        jLabel13.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Edad:");
        pnnombre.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 90, 20));

        jLabel14.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Telefono:");
        pnnombre.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 90, 20));
        pnnombre.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 250, 120));

        jButton11.setText("Guardar");
        pnnombre.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, 150, 60));
        pnnombre.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 160, 30));
        pnnombre.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 160, 30));

        jLabel17.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Dui");
        pnnombre.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 90, 20));
        pnnombre.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 160, 30));

        pncliente.add(pnnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, -30, 290, 10000));

        pntabla.setOpaque(false);
        pntabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtbuscarC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarCKeyReleased(evt);
            }
        });
        pntabla.add(txtbuscarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 570, 30));

        jButton12.setText("Eliminar");
        pntabla.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 150, 40));

        tblMcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblMcliente);

        pntabla.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 700, 520));

        pncliente.add(pntabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 800, 740));

        getContentPane().add(pncliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 1100, 730));

        PnMenu.setBackground(new java.awt.Color(52, 52, 52));
        PnMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        PnMenu.setForeground(new java.awt.Color(255, 166, 33));
        PnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVentas.setBackground(new java.awt.Color(102, 102, 102));
        btnVentas.setFont(new java.awt.Font("GodOfWar", 0, 24)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas blanco.png"))); // NOI18N
        btnVentas.setBorder(null);
        btnVentas.setContentAreaFilled(false);
        btnVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVentas.setIconTextGap(40);
        btnVentas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas one.png"))); // NOI18N
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        PnMenu.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 280, 70));

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientes blanca.png"))); // NOI18N
        btnCliente.setBorderPainted(false);
        btnCliente.setContentAreaFilled(false);
        btnCliente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientes gris.png"))); // NOI18N
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        PnMenu.add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 270, 70));

        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/producto blanco.png"))); // NOI18N
        btnProductos.setBorderPainted(false);
        btnProductos.setContentAreaFilled(false);
        btnProductos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/producto gris.png"))); // NOI18N
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        PnMenu.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 260, 70));

        btnAbono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abono blanco.png"))); // NOI18N
        btnAbono.setBorderPainted(false);
        btnAbono.setContentAreaFilled(false);
        btnAbono.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abono gris.png"))); // NOI18N
        btnAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbonoActionPerformed(evt);
            }
        });
        PnMenu.add(btnAbono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 240, 70));

        BtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar sesionblanco.png"))); // NOI18N
        BtnCerrar.setBorderPainted(false);
        BtnCerrar.setContentAreaFilled(false);
        BtnCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar sesion gris.png"))); // NOI18N
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });
        PnMenu.add(BtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 270, 70));

        lblSelect.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        PnMenu.add(lblSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, 70));

        lblSelect1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        PnMenu.add(lblSelect1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, 70));

        lblSelect2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        PnMenu.add(lblSelect2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, 70));

        lblSelect3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        PnMenu.add(lblSelect3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, 70));

        getContentPane().add(PnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 50, 280, 720));

        lblFondo.setBackground(new java.awt.Color(102, 102, 102));
        lblFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblFondo.setMaximumSize(new java.awt.Dimension(1111, 800));
        lblFondo.setOpaque(true);
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1380, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
      
      Animacion an = new Animacion();
      int x = PnMenu.getX();
      if(x == 0){        
   
          an.mover_izquierda(0, -180, 10, 5, PnMenu);
          an.mover_izquierda(280, 150, 10, 5, pnventa);
             
      }
      else{
    
          an.mover_derecha(-180, 0, 5, 2, PnMenu);
          an.mover_derecha(150, 280, 5, 2, pnventa);
       
      }
       
    }//GEN-LAST:event_btnMenuActionPerformed
static void inventariotabala(){
    
}
    
    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
 
        lblSelect.setVisible(true);
        lblSelect1.setVisible(false);
         lblSelect2.setVisible(false);
          lblSelect3.setVisible(false);
     
           pnventa.setVisible(true);
           pncliente.setVisible(false);
          pnProducto.setVisible(false);
    }//GEN-LAST:event_btnVentasActionPerformed

    
void fecha(){
   try {
    String time;
    int dia,mes,año;
Calendar fecha = Calendar.getInstance();
dia = fecha.get(Calendar.DAY_OF_MONTH);
mes =fecha.get(Calendar.MONTH);
año= fecha.get(Calendar.YEAR);
time = dia+"/"+mes+"/"+año;
java.util.Date fechaParseada;
        
            fechaParseada = new SimpleDateFormat("dd/mm/yyyy").parse(time);
            calendario.setDate(fechaParseada);
        } catch (ParseException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        }

}

 
    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        
        lblSelect.setVisible(false);
        lblSelect1.setVisible(true);
         lblSelect2.setVisible(false);
          lblSelect3.setVisible(false);
   
            pnventa.setVisible(false);
           pncliente.setVisible(true);
         pnProducto.setVisible(false);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
                
        lblSelect.setVisible(false);
        lblSelect1.setVisible(false);
         lblSelect2.setVisible(true);
          lblSelect3.setVisible(false);
      pnventa.setVisible(false);
           pncliente.setVisible(false);
           pnProducto.setVisible(true);

    }//GEN-LAST:event_btnProductosActionPerformed
 
    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
           Login lg= new Login();
           int respuesta;
           respuesta = JOptionPane.showConfirmDialog(null, "Desea Cerrar Sesión?","Cerrar Sesión",0);
          if(respuesta == 0){
           lg.setVisible(true);
           this.dispose();
          }      
    }//GEN-LAST:event_BtnCerrarActionPerformed

    private void btnAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbonoActionPerformed
           
        lblSelect.setVisible(false);
        lblSelect1.setVisible(false);
         lblSelect2.setVisible(false);
          lblSelect3.setVisible(true);
        
            
    }//GEN-LAST:event_btnAbonoActionPerformed
  
 
    
    private void txtproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductoActionPerformed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Tpersona per= new Tpersona();
        
      per.setVisible(true);
    
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
      
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       txtCliente.setText("");
       txtdireccion.setText("");
       txtDui.setText("");
       txtprecio.setText("");
       txtTotal.setText("");
       txtproducto.setText("");
       txtCantidad.setText("1");
       calendario.setDate(null);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void bntAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAgregarClienteActionPerformed

    }//GEN-LAST:event_bntAgregarClienteActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

    }//GEN-LAST:event_jButton8ActionPerformed

    void tabla(){
        JTableHeader th = tblventa.getTableHeader();
        Font fuente = new Font("Century Schoolbook", Font.PLAIN, 14);
th.setFont(fuente); 
    }
    private void btnAgregaProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregaProActionPerformed
String producto;
int cantidad;
double precio;
int fila,existe ;
fila = 0;
existe =0;
if((txtproducto.getText().equals("")&&txtprecio.getText().equals("")&&txtTotal.getText().equals(""))==false){
producto = txtproducto.getText();
cantidad = Integer.parseInt(txtCantidad.getText());
precio =Double.parseDouble(txtTotal.getText());

DefaultTableModel modelo = (DefaultTableModel) tblventa.getModel();
String registros[] = new String[5];
registros[0] = producto;
registros[1] = String.valueOf(cantidad);
registros[2] = String.valueOf(precio);
registros[3] = String.valueOf(String.format("%.2f",precio * cantidad));

if(precio>=preciocompra){
 if(tblventa.getRowCount() == 0){
 modelo.addRow(registros);
 calculartotal();
 }
 else{
 for (int i = 0; i < tblventa.getRowCount(); i++) {
 if(tblventa.getValueAt(i, 0).toString().equals(registros[0])){
     existe = 1;
     fila = i;
 }
 }
 if(existe == 1){
 int ncantidad = Integer.parseInt(tblventa.getValueAt(fila, 1).toString())+Integer.parseInt(registros[1]);
double Total =Double.parseDouble(tblventa.getValueAt(fila, 2).toString())*ncantidad;
 modelo.setValueAt(ncantidad , fila, 1);
  modelo.setValueAt(Total , fila, 3);
    calculartotal();
  existe= 0;
 }else{
 modelo.addRow(registros);
   calculartotal();
 }
 }
txtprecio.setText("");
       txtTotal.setText("");
       txtproducto.setText("");
       txtCantidad.setText("1"); 
}
else{
JOptionPane.showMessageDialog(null, "El precion de venta esta muy bajo");
}
}
else{
JOptionPane.showMessageDialog(null, "por favor selecciona un producto");
}
    }//GEN-LAST:event_btnAgregaProActionPerformed
         void calculartotal(){
             double total1,total2 ;
             total2=0;
             for (int i = 0; i < tblventa.getRowCount(); i++) {
                total1= Double.parseDouble(tblventa.getValueAt(i, 3).toString());
                total2 = total2+total1;
             }
             TxtTotalventa.setText(String.valueOf(String.format("%.2f",total2)));
         }
    
    String filasCombo[] = new String[2];
    String array[] = new String[6];
    int contadors = 0;
    void cargarcombo() {
       MostrarEmpleado me = new MostrarEmpleado();
        ArrayList<Empleado> PS = me.MostrarEmpleados();
        Iterator i = PS.iterator();
        DefaultComboBoxModel DefaultComboBoxModel = new DefaultComboBoxModel();
        DefaultComboBoxModel.removeAllElements();
        while (i.hasNext()) {
            Empleado e;
            e = (Empleado) i.next();
            array[contadors] = String.valueOf(e.getID_empleado());
            filasCombo[1] = e.getEmpleado();
            DefaultComboBoxModel.addElement(e.getEmpleado());
            contadors++;
        }
        CBXVendedor.setModel(DefaultComboBoxModel);

    }
    void buscar(){
     String Titulo[]={"ID","Cliente","Dui","Edad","Telefono","Direccion"};
DefaultTableModel bc = new DefaultTableModel(null, Titulo){
    @Override
    public boolean isCellEditable(int row, int column) {
        return false;
    }
};
        Clientes cl = new Clientes();
    cl.setNombre(txtbuscarC.getText());
    MostrarCliente mc = new MostrarCliente();
    ArrayList<Clientes> Cl= mc.BuscarClientes(cl);
    Iterator i =  Cl.iterator();
    String Filas[] = new String[6];
    while (i.hasNext()) {        
        Clientes c;
        c= (Clientes)i.next();
        Filas[0]=String.valueOf(c.getId_Cliente());
        Filas[1]= c.getNombre();
        Filas[2]=c.getDui();
        Filas[3]=String.valueOf(c.getEdad());
        Filas[4]=c.getTelefono();
        Filas[5]=c.getDireccion();
        bc.addRow(Filas);
         
    }
  
tblMcliente.setModel(bc);
       
}
    private void btnbuscarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarProductosActionPerformed
        FrmProductos pro = new FrmProductos();
        pro.setVisible(true);
    }//GEN-LAST:event_btnbuscarProductosActionPerformed

    private void bntmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntmenosActionPerformed
        int numero;
        numero = Integer.parseInt(txtCantidad.getText());
        if(numero >= 2 && numero <=10){
        txtCantidad.setText( String.valueOf(numero-1));
        }
       
    }//GEN-LAST:event_bntmenosActionPerformed

    private void bntAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAgregarActionPerformed
        int numero,limite=0,existe=0,fila=0, cantidad;
      
        numero = Integer.parseInt(txtCantidad.getText());
        for (int i = 0; i < tblventa.getRowCount(); i++) {
     if(tblventa.getValueAt(i, 0).toString().equals(txtproducto.getText())){
     existe =1 ;
     fila = i;
 }
 }      if(existe ==0){
        if (inventario>10) {
        if(numero >= 1 && numero <10){
        txtCantidad.setText( String.valueOf(numero+1));
        }
         }
        else if(numero>=1 && numero<inventario){
        txtCantidad.setText( String.valueOf(numero+1));
        }
 } else if(existe ==1){
       cantidad = Integer.parseInt(tblventa.getValueAt(fila, 1).toString());
 if (inventario>cantidad){
 limite = inventario - cantidad;
 if(numero >= 1 && numero <limite){
        txtCantidad.setText( String.valueOf(numero+1));
        }
 }
 
 }
    }//GEN-LAST:event_bntAgregarActionPerformed

    private void txtbuscarCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarCKeyReleased
        buscar();
    }//GEN-LAST:event_txtbuscarCKeyReleased

    private void txtbuscarproKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarproKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarproKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }
    
     public void buscarproducto(){
     String Titulo[]={"ID","Producto","Serie","Precio","Marca","Descripcion","Proveedor","Inventario"};
DefaultTableModel bc = new DefaultTableModel(null, Titulo){
    @Override
    public boolean isCellEditable(int row, int column) {
        return false;
    }
};
        Productovista pr = new Productovista();
    pr.setSerie(txtbuscarpro.getText());
    MostrarProductos mp = new MostrarProductos();
    ArrayList<Productovista> Cl= mp.BuscarProducto(pr);
    Iterator i =  Cl.iterator();
    String Filas[] = new String[8];
    while (i.hasNext()) {        
        Productovista p;
        p= (Productovista)i.next();
        Filas[0]=String.valueOf(p.getId_Producto());
        Filas[1]= p.getProducto();
        Filas[2]=p.getSerie();
        Filas[3]=String.valueOf(p.getPrecio());
        Filas[4]=p.getMarca();
         Filas[5]=p.getDescripcion();
           Filas[6]=p.getProveedor();
             Filas[7]=String.valueOf(p.getInventario());
        bc.addRow(Filas);
         
    }
  
tblProducto.setModel(bc);
        tabla();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JComboBox<String> CBXVendedor;
    private javax.swing.JPanel PnBarra;
    private javax.swing.JPanel PnMenu;
    private javax.swing.JTabbedPane TpVentas;
    private javax.swing.JTextField TxtTotalventa;
    private javax.swing.JButton bntAgregar;
    private javax.swing.JButton bntAgregarCliente;
    private javax.swing.JButton bntmenos;
    private javax.swing.JButton btnAbono;
    private javax.swing.JButton btnAgregaPro;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnVentas;
    private javax.swing.JButton btnbuscarProductos;
    private com.toedter.calendar.JDateChooser calendario;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblSelect;
    private javax.swing.JLabel lblSelect1;
    private javax.swing.JLabel lblSelect2;
    private javax.swing.JLabel lblSelect3;
    public static javax.swing.JPanel pnProducto;
    public static javax.swing.JPanel pncliente;
    private javax.swing.JPanel pnnombre;
    private javax.swing.JPanel pntabla;
    private javax.swing.JPanel pntabla1;
    private javax.swing.JPanel pnventa;
    private javax.swing.JTable tblMcliente;
    public static javax.swing.JTable tblProducto;
    public static javax.swing.JTable tblventa;
    private javax.swing.JTextField txtCantidad;
    public static javax.swing.JTextField txtCliente;
    public static javax.swing.JTextField txtDui;
    public static javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtbuscarC;
    private javax.swing.JTextField txtbuscarpro;
    public static javax.swing.JTextField txtdireccion;
    public static javax.swing.JTextField txtprecio;
    public static javax.swing.JTextField txtproducto;
    // End of variables declaration//GEN-END:variables
}
